### ISSUE TITLE
Cocoapods.org only reflects v1.5

### ISSUE THREAD

**Issue by rushk2112** [vuvankhac/KVLoading#2]
To use the Swift 4 version (1.6) you have to use:

pod 'KVLoading', :git => 'https://github.com/vuvankhac/KVLoading.git', :branch => 'master'

instead of:

pod 'KVLoading', '~> 1.6'

Cocoapods does not find a version 1.6 and only lists 1.5 when searching.

**Comment by vuvankhac** [comment]
@rushk2112 It's ok right now, please check it again.

**Comment by rushk2112** [comment]
Everything looks great! Thanks!

**Comment by vuvankhac** [comment]
@rushk2112 you're welcome.
